[project]
name = "cs50w-pset1"
version = "0.1.0"
description = "Source code for CS50W's Problem Set 1: Wiki"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.5",
    "markdown2>=2.5.4",
]
